create table public.user_info (
  id uuid not null,
  created_at timestamp with time zone not null default now(),
  role text null,
  name text null,
  last_name text null,
  birthday date null,
  phone text null,
  height numeric null,
  weight numeric null,
  blood_type public.blood_type null,
  next_date date null,
  status text null default 'active'::text,
  email text null,
  is_complete boolean not null default false,
  id_nivel uuid null default 'bf866e5b-ae68-4c5c-a1a4-3741db9a6ef1'::uuid,
  puntos bigint null default '0'::bigint,
  constraint usuarios_pkey primary key (id),
  constraint user_info_id_nivel_fkey foreign KEY (id_nivel) references nivel (id),
  constraint usuarios_id_fkey foreign KEY (id) references auth.users (id)
) TABLESPACE pg_default;

create table public.entidad (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  nombre character varying null,
  imagen character varying null,
  status character varying null,
  id_usuario uuid null,
  constraint entidad_pkey primary key (id),
  constraint entidad_id_fkey foreign KEY (id) references user_info (id)
) TABLESPACE pg_default;

create table public.locacion (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  nombre character varying null,
  direccion character varying null,
  longitud double precision null,
  latitud double precision null,
  map_link character varying null,
  status character varying null,
  id_entidad uuid null,
  constraint locacion_pkey primary key (id),
  constraint locacion_id_entidad_fkey foreign KEY (id_entidad) references entidad (id)
) TABLESPACE pg_default;

create table public.campana (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  tipo character varying null,
  componente character varying null,
  descripcion character varying null,
  fecha_inicio timestamp with time zone null,
  fecha_fin timestamp with time zone null,
  status character varying null,
  id_locacion uuid null default gen_random_uuid (),
  constraint campaña_pkey primary key (id),
  constraint campaña_id_locacion_fkey foreign KEY (id_locacion) references locacion (id)
) TABLESPACE pg_default;

create table public.registro (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  status character varying null,
  fecha_validacion timestamp with time zone null,
  id_usuario uuid null,
  id_campana uuid null,
  constraint registro_pkey primary key (id),
  constraint registro_id_campana_fkey foreign KEY (id_campana) references "campaña" (id),
  constraint registro_id_usuario_fkey foreign KEY (id_usuario) references user_info (id)
) TABLESPACE pg_default;

create table public.nivel (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  nombre character varying null,
  puntaje_minimo bigint null,
  constraint nivel_pkey primary key (id)
) TABLESPACE pg_default;

create table public.premio (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  puntaje bigint null,
  id_usuario uuid null,
  constraint premio_pkey primary key (id),
  constraint premio_id_usuario_fkey foreign KEY (id_usuario) references user_info (id)
) TABLESPACE pg_default;
